name: React-deploy
 
on:
  push:
   branches:
    - feature/deployment
    - feature/github-actions
    - feature/jenkins

  pull_requests:
   branches:
    - feature/deployment
    - feature/github-actions
    - feature/jenkins
  
jobs:
  test:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t react-lab-test -f Dockerfile.dev .

    - name: Run Tests
      run: docker run -e CI=true react-lab-test npm run test  




